### ISSUE TITLE
【store】数据取值丢失

### ISSUE THREAD

**Issue by namedWJ** [didi/Hummer#102]
## 描述
store初始化的字段，如果字段初始值为null或undefined，页面跳转时，store内初始化字段对应的属性丢失
## Hummer version:
1.2.2

## 复现步骤
1.在state.js里初始化一个 {orderDetail: null}
2.在页面中，声明...store.mapState({orderDetail => state.orderDetail}) 
取值：console.log(this.orderDetail) // 显示为undefined
console.log(Object.keys(store.state)) // 里面没有orderDetail

## 预期结果
object.keys(store.state) 中应该有orderDetail

**Comment by duanlikang** [comment]
感谢反馈，看描述是 `Tenon Store`在页面跳转时，重新 init Store 时产生非预期问题，具体原因我们这边排查下。

**Comment by namedWJ** [comment]
> 感谢反馈，看描述是 `Tenon Store`在页面跳转时，重新 init Store 时产生非预期问题，具体原因我们这边排查下。

wooo  这回复速度 可以的   那就麻烦尽快了哈

**Comment by duanlikang** [comment]
问题原因是由于 Store初始化数据的时候，会将序列化后的数据放到内存中，序列化时会导致值`undefined`的属性丢失。跳转到新的页面的时候，重新从内存中加载数据，会造成数据的丢失。

解决方案是
序列化的时候，通过自定义 `stringify`和`parse`函数，处理 `undefined`的值。
