### ISSUE TITLE
iOS 中 Dialog 组件多个实例相互覆盖

### ISSUE THREAD

**Issue by duanlikang** [didi/Hummer#103]
## 描述
iOS 中 Dialog 组件多个实例会相互覆盖
比如，同时存在两个实例，前一个实例展示，后一个实例不展示，预期效果是展示前一个实例，但是iOS中无法展示，Android 中展示正常
## Hummer version:

最新版本
## 复现步骤

1.创建两个 Dialog实例
## 样例代码、屏幕截图或者仓库链接
<!-- 请提供一个 GitHub 仓库链接或者提供一段最小复现代码。

**Comment by bbssyyuui** [comment]
iOS 侧的Dialog问题还未修复

**Comment by bbssyyuui** [comment]
iOS 侧Dialog问题已修复
