### ISSUE TITLE
Hummer 支持 Canvas

### ISSUE THREAD

**Issue by duanlikang** [didi/Hummer#113]
## 功能请求

Hummer 支持 Canvas 的相关 Api
- [x] 我想要完成此功能

**您的功能请求是否与一个问题有关？**

我有一个问题，业务场景中需要通过 canvas 实现进度条，类似如下：
![image](https://user-images.githubusercontent.com/10548952/112955344-e852bb00-9171-11eb-87cb-2615a4f8bf12.png)

**描述您希望的解决方案**
Hummer 侧提供 Canvas 组件，暴露出 Canvas 的各种api，支持绘制；
Tenon 侧实现 Canvas 标签，通过 ref 的方式拿到实例，进行绘制。

**Comment by chenyulun** [comment]
尽肯能的实现h5的canvas的属性和API

**Comment by duanlikang** [comment]
> 尽肯能的实现h5的canvas的属性和API

整体 API 设计的时候，会以 H5 的canvas API 为标准，进行对齐，便于 H5 基于 Canvas 的库和框架，可以实现无缝的接入。

**Comment by chenyulun** [comment]
canvas能不能快点排期做，我们想使用echarts或者Highcharts组件库

**Comment by bbssyyuui** [comment]
已实现canvas功能
