### ISSUE TITLE
请求加入sqlite组件

### ISSUE THREAD

**Issue by XiaoCC** [didi/Hummer#116]
## 功能请求

- [ ] 我想要完成此功能

**您的功能请求是否与一个问题有关？**

我有一个问题，开发离线功能的app时需要操作本地sqlite，请问能否加入sqlite数据库的组件，谢谢🙏
**描述您希望的解决方案**
希望ios和Android都能加入sqlite数据库的组件。
**描述您考虑过的备选方案**.

**文档、适配、迁移策略**

**Comment by bbssyyuui** [comment]
你好\~感谢你的反馈。目前Hummer SDK中还没有操作本地sqlite相关的API，暂时需要通过Hummer的扩展机制，即[自定义导出组件的方式](https://hummer.didi.cn/doc#/zh-CN/android_doc#zi-ding-yi-dao-chu-lei)来使用（原生两端自己实现相关功能，并把API导出到JS侧，供JS使用）。同时也非常欢迎给我们提交相关PR，一起共建Hummer\~
