### ISSUE TITLE
是否支持文件缓存到用户侧本地

### ISSUE THREAD

**Issue by Hanwencc** [didi/Hummer#117]
## 功能请求
需要开发完整离线的应用，需要缓存音乐以及视频到本地。
在Hummer文档中没有看到有相关缓存api以及缓存管理api。
不知是否有计划进行适配。

**Comment by bbssyyuui** [comment]
你好~感谢你的反馈。目前Hummer SDK中还没有文件缓存相关的API，暂时需要通过Hummer的扩展机制，即[自定义导出组件的方式](https://hummer.didi.cn/doc#/zh-CN/android_doc#zi-ding-yi-dao-chu-lei)来使用（原生两端自己实现相关功能，并把API导出到JS侧，供JS使用）。同时也非常欢迎给我们提交相关PR，一起共建Hummer~
