### ISSUE TITLE
iOS端需完善onBack生命周期

### ISSUE THREAD

**Issue by AdamCaoQAQ** [didi/Hummer#118]
## 功能请求

- [ ] 我想要完成此功能
Tenon-vue mixins onBack生命周期执行顺序优化
hummer  iOS sdk 原生支持onBack生命周期

**文档、适配、迁移策略**

**Comment by duanlikang** [comment]
Tenon Vue  全局 Mixin 针对 onBack 生命周期进行特殊处理。
针对多个Mixin 注册的onBack 函数，规则如下：
1.  Mixin 通过 Tenon.mixin() 进行注册，执行时按照注册的先后顺序进行执行。
2.  函数返回 true 时，后续函数不再执行；返回 false时，依次执行。

**Comment by bbssyyuui** [comment]
iOS 侧的 onBack 功能还没补齐

**Comment by yFeii** [comment]
[](url)
