### ISSUE TITLE
More than one file was found with OS independent path 'lib/x86/libc++_shared.so'

### ISSUE THREAD

**Issue by YoungLea30** [didi/Hummer#122]
## 描述
![image](https://user-images.githubusercontent.com/33273491/114825945-6ad9ac80-9df9-11eb-956e-fcb50821fd64.png)
 
## Hummer version:
0.3.15

## 复现步骤
build构建项目的时候会报错

## 问题原因
因为自己项目也使用了c++的标准库libc++_shared.so, hummer也引入了该库所以导致了冲突

## 解决方案
在app的build.gradle作如下配置
android{
       packagingOptions {
                   //只选择一个libc++_shared.so
                   pickFirst '**/libc++_shared.so'
       }
}

**Comment by RookieDailyLi** [comment]
其实这个不算是hummer的bug,公司项目集成发现了就提一下,免得其他小伙伴踩坑

**Comment by bbssyyuui** [comment]
嗯，很多三方库都会内部都会用到libc++_shared.so库，当你的项目中依赖了多个这种三方库的时候，就会有多个libc++_shared.so库产生冲突，解决方案就是只取第一个：
```
android{
    packagingOptions {
        pickFirst '**/libc++_shared.so'
    }
}
```
