### ISSUE TITLE
pending exception java.lang.NoSuchMethodError: No virtual method load(Ljava/lang/String;)Lcom/bumptech/glide/DrawableTypeRequest;

### ISSUE THREAD

**Issue by YoungLea30** [didi/Hummer#123]
## Hummer version:
0.3.15

##报错截图
![image](https://user-images.githubusercontent.com/33273491/114832480-1c301080-9e01-11eb-9939-1e3d7bcf6449.png)

## 原因
我们的项目引入了glide版本是4.11.0该版本删除了一些老版本的类,hummer使用的glide版本较老,导致hummer的图片加载时有些类和方法找不到

## 复现步骤
js上加载一张网络图片会报错

## 解决方案
![image](https://user-images.githubusercontent.com/33273491/114828772-de30ed80-9dfc-11eb-851b-69f88da61cab.png)
自定义ImageLoaderAdapter, 基本上都是复制hummer sdk自带的DefaultImageLoaderAdapter,只是改了一下加载gif、drawable的地方
package com.bokecc.hummer;

import android.graphics.drawable.Drawable;
import android.widget.ImageView;

import androidx.annotation.NonNull;
import androidx.annotation.Nullable;

import com.bumptech.glide.Glide;
import com.bumptech.glide.load.resource.gif.GifDrawable;
import com.bumptech.glide.request.target.SimpleTarget;
import com.bumptech.glide.request.transition.Transition;
import com.didi.hummer.HummerSDK;
import com.didi.hummer.adapter.imageloader.DrawableCallback;
import com.didi.hummer.adapter.imageloader.IImageLoaderAdapter;
/**
* @author liyong312999538@163.com
* @date 4/15/21
* @desc hummer图片加载适配器
*/
public class HummerDefaultImageLoaderAdapter implements IImageLoaderAdapter {

    @Override
    public void setImage(String url, ImageView view) {
        try {
            Glide.with(view.getContext()).load(url).into(view);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    @Override
    public void setGif(String url, int repeatCount, ImageView view) {
        // 设置为无限循环
        if (repeatCount == 0) {
            repeatCount = GifDrawable.LOOP_FOREVER;
        }
        try {
            int finalRepeatCount = repeatCount;
            Glide.with(view.getContext()).asGif().load(url).into(new SimpleTarget<GifDrawable>() {
                @Override
                public void onResourceReady(@NonNull GifDrawable resource, @Nullable Transition<? super GifDrawable> transition) {
                    resource.setLoopCount(finalRepeatCount);
                    view.setImageDrawable(resource);
                    resource.start();
                }
            });
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    @Override
    public void setImage(int resId, ImageView view) {
        try {
            Glide.with(view.getContext()).load(resId).into(view);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    @Override
    public void setGif(int resId, int repeatCount, ImageView view) {
        // 设置为无限循环
        if (repeatCount == 0) {
            repeatCount = GifDrawable.LOOP_FOREVER;
        }
        try {
            int finalRepeatCount = repeatCount;
            Glide.with(view.getContext()).asGif().load(resId).into(new SimpleTarget<GifDrawable>() {
                @Override
                public void onResourceReady(@NonNull GifDrawable resource, @Nullable Transition<? super GifDrawable> transition) {
                    resource.setLoopCount(finalRepeatCount);
                    view.setImageDrawable(resource);
                    resource.start();
                }
            });
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    @Override
    public void loadDrawable(String url, DrawableCallback callback) {
        try {
            Glide.with(HummerSDK.appContext).load(url).into(new SimpleTarget<Drawable>() {
                @Override
                public void onResourceReady(@NonNull Drawable resource, @Nullable Transition<? super Drawable> transition) {
                    if (callback != null) {
                        callback.onDrawableLoaded(resource);
                    }
                }
            });
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    @Override
    public void loadDrawable(int resId, DrawableCallback callback) {
        try {
            Glide.with(HummerSDK.appContext).load(resId).into(new SimpleTarget<Drawable>() {
                @Override
                public void onResourceReady(@NonNull Drawable resource, @Nullable Transition<? super Drawable> transition) {
                    if (callback != null) {
                        callback.onDrawableLoaded(resource);
                    }
                }
            });
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}

**Comment by RookieDailyLi** [comment]
其实不算是humemr的bug,就是个库冲突问题,希望官方后续升级一下sdk的glide版本

**Comment by bbssyyuui** [comment]
关于glide的版本，Hummer SDK 无法做到适配所有接入方的版本，所有glide的版本暂时不会考虑升级。
但是你可以通过设置自定义ImageLoaderAdapter的方式来解决这个问题：
```
HummerConfig config = new HummerConfig.Builder()
                .setImageLoaderAdapter(new YourImageLoaderAdapter())
                .builder();
Hummer.init(context, config);
```
