### ISSUE TITLE
list的点击事件当cell复用的时候,一次点击会执行多次

### ISSUE THREAD

**Issue by YoungLea30** [didi/Hummer#124]
## Hummer version:
0.3.15

## 复现步骤
在list的onUpdate中addEvent(),一次点击当cell复用的时候会执行多次
![image](https://user-images.githubusercontent.com/33273491/114834415-1a674c80-9e03-11eb-9a0e-0179ba94a057.png)
![image](https://user-images.githubusercontent.com/33273491/114834467-28b56880-9e03-11eb-9c53-28e1e530e0fd.png)

## 预期结果
addEvent()之前可以先调一下removeEvent()

**Comment by bbssyyuui** [comment]
我们设计View的addEventListener的时候，本就是支持同一种type可以设置多个callback的，所以在List组件这种场景下，不建议在onUpdate回调中反复多次设置callback，而是在onCreate回调中设置一次callback。
