### ISSUE TITLE
iOS 端无法调试 TS 和 Vue 工程代码

### ISSUE THREAD

**Issue by bbssyyuui** [didi/Hummer#133]
## 描述

iOS 端无法调试 TS 和 Vue 工程代码。

## 复现步骤

1. 创建TS 或 Vue 工程，并开启调试模式；
2. 无法正常显示页面，也无法正常调试；

## 预期结果

可以正常调试

**Comment by yFeii** [comment]
see https://github.com/didi/Hummer/commit/71c6b706f3d9d0aba2406ebbfd1d3b1ced727f8f
