### ISSUE TITLE
iOS 端图片加载需要支持设置自定义图片加载适配器，可以替换成其他图片加载库

### ISSUE THREAD

**Issue by bbssyyuui** [didi/Hummer#134]
## 描述

iOS 端图片加载需要支持设置自定义图片加载适配器，可以替换成其他图片加载库。

## Hummer version:

最新版本

## 预期结果

可以把Hummer SDK中默认的图片加载库，替换成其他图片加载库

**Comment by yFeii** [comment]
以提供 自定义 loader decoder
