### ISSUE TITLE
tenon代码内联样式style中的border样式没有覆盖class样式中的border样式

### ISSUE THREAD

**Issue by JohnsenZhou** [didi/Hummer#136]
<view class='daijia-cell-content' style="{{contentStyle}}">

contentStyle: 'border: none;'

.daijia-cell-content {
  border: 1px solid #cccccc;
}

但是最后还是显示了border

**Comment by duanlikang** [comment]
本质原因是由于 Tenon 针对`border:none`和`border:0`的简写场景没有做处理，这个下个版本修复。

**Comment by duanlikang** [comment]
参考 [MDN 文档](https://developer.mozilla.org/en-US/docs/Web/CSS/border)

支持的类型：`width | style | color`
> The border property may be specified using one, two, or three of the values listed below. The order of the values does not matter.
