### ISSUE TITLE
Button控件暂时没有提供设置粗体的接口

### ISSUE THREAD

**Issue by flynn89** [didi/Hummer#137]
## 功能请求

- [ ] 我想要完成此功能

**您的功能请求是否与一个问题有关？**

**描述您希望的解决方案**

**描述您考虑过的备选方案**.

**文档、适配、迁移策略**

**Comment by duanlikang** [comment]
感谢反馈，我们会在下一个版本中进行功能补齐。建议可以先用 `text`模拟实现 `Button`

**Comment by bbssyyuui** [comment]
由于初始设计原因，Button只实现了比较简单的几个文本相关的样式，如果需要使用完整的文本相关样式，请使用Text组件。Button中的样式暂时不做补齐。
