### ISSUE TITLE
有个地方可以错误集中处理

### ISSUE THREAD

**Issue by isscaorz** [didi/Hummer#148]
## 功能请求

- [ ] 有地方可以捕获到error集中处理，如vue中的errorCaptured一样

**您的功能请求是否与一个问题有关？**

**描述您希望的解决方案**

**描述您考虑过的备选方案**.

**文档、适配、迁移策略**

**Comment by duanlikang** [comment]
Vue3 文档 https://vue3js.cn/docs/zh/api/application-config.html#errorhandler

**Comment by duanlikang** [comment]
编写错误捕获插件，通过 use 的方式进行插件的引用

**Comment by duanlikang** [comment]
在 [issue](https://github.com/didi/Hummer/issues/153)中跟进处理
