### ISSUE TITLE
hummer init失败

### ISSUE THREAD

**Issue by krait-yxin** [didi/Hummer#15]
npm registry指向didi内部域名 无法拉取模版工程
<img width="669" alt="Screen Shot 2021-01-08 at 10 15 11 PM" src="https://user-images.githubusercontent.com/4286425/104025172-30abae00-51ff-11eb-88ee-8e245bc57e3f.png">

**Comment by iFarSeer** [comment]
➜  Project hummer init
? Which template do you want init? template-ts
? Project name ts
⠋ Get template version and download...(node:47838) UnhandledPromiseRejectionWarning: Error: Command failed: npm pack @hummer/cli-template-ts@0.0.3 --registry=http://npm.intra.xiaojukeji.com
npm ERR! code ENOTFOUND
npm ERR! errno ENOTFOUND
npm ERR! network request to http://npm.intra.xiaojukeji.com/@hummer%2fcli-template-ts failed, reason: getaddrinfo ENOTFOUND npm.intra.xiaojukeji.com
npm ERR! network This is a problem related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'

**Comment by duanlikang** [comment]
感谢反馈问题，这个问题我们已经修复，可以升级下 Cli，执行命令`npm install @hummer/cli -g`或者 `npm update @hummer/cli -g`
