### ISSUE TITLE
@hummer/cli@0.1.5 创建新工程后安装依赖失败

### ISSUE THREAD

**Issue by XiangliJiaxing** [didi/Hummer#16]
选择的工程类型为： vue

日志如下： 

npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.com/@didi%2ftenon-core - Not found
npm ERR! 404
npm ERR! 404  '@didi/tenon-core@^1.0.0' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Administrator\AppData\Roaming\npm-cache\_logs\2021-01-11T03_48_29_632Z-debug.log

@didi/tenon-core 在npm、cnpm 上均未能找到

**Comment by duanlikang** [comment]
感谢反馈问题，现在 Tenon 相关包已经发布，这个问题已经解决。
建议您按照以下步骤，进行操作
1. 重新安装 hummer cli，用于更新 tenon loader 相关包。执行命令 `npm install @hummer/cli -g`
2.由于 Tenon Vue 模板有更新，建议您重新 init vue 项目
3.在创建的仓库里面，执行 `npm install`
如果仍有问题，欢迎反馈。
