### ISSUE TITLE
ios <textarea />Tenon组件 ，输入文字后第一个文字消失，绑定异常

### ISSUE THREAD

**Issue by JavaXinTu** [didi/Hummer#199]
## 描述

ios <textarea />Tenon组件 ，输入文字后第一个文字消失，绑定异常。

## Hummer version:

@hummer/cli@0.1.26

## 复现步骤

1.第一个输入的内容，会消失，然后绑定失效，无法获取内容值。
2.设有默认值，不操作的情况下可以获取绑定值，但是输入第一个文字，会覆盖并消失之前和当前的第一个字，然后绑定异常，变量都会消失。

## 预期结果

正常使用该组件，绑定关系正常

## 样例代码、屏幕截图或者库链接

`<template>
  <view class="page">
    <view class="demo-header">
      
    </view>
    <view class="demo-container">
      <view class="demo-item flex-container">
        <view class="p-item-title">
          <text class="p_item-title-text">备注</text>
        </view>
        <view class="p-item-content">
          <textarea
            class="input input-place input-textarea"
            rows="3"
            v-model="remark"
            placeholder=""
          />
        </view>
      </view>
    </view>
    <view class="item-foot">
      <button class="foot-btn" @tap="success">确定</button>
      <button class="foot-btn" @tap="reset">清除</button>
    </view>
  </view>
</template>
<style lang="less" scoped>
// @import "../common/assets/css/common.less

.page{
  width: 100%;
  height: 100%;
}
.demo-header {
  display: flex;
  height: 100hm;
  background-color: #2f86f6;
}
.demo-item {
  background-color: #ffffff;
  width: 100%;
  margin-bottom: 0.2rem;
  padding: 0.2rem 0;
}
.flex-container {
  display: flex;
  justify-content: space-between;
}
.p-item-title {
  width: 22%;
  flex: 1;
  padding-left: 0.2rem;
}
.p-item-content {
  width: 78%;
  flex: 3.4;
}
.p_item-title-text {
  height: 0.8rem;
  text-align: left;
}
.item-btn {
  width: 98%;
  height: 0.8rem;
  text-align: center;
  color: white;
  background: #2f86f6;
  border-radius: 10px;
}
.demo-container {
  margin-top: 0.01rem;
}
.demo-item {
  margin-bottom: 0.01rem;
}
.input-disabled {
  background-color: #eee;
}
.input-textarea {
  border-style: solid;
  border-width: 1px;
  border-color: #ddd;
  border-radius: 0.1rem;
  width: 98%;
  height: 1.8rem;
  padding-left: 2px;
}
.item-foot {
  width: 100%;
  height: 1.2rem;
  background-color: #ffffff;
  display: flex;
  position: fixed;
  bottom: 0;
  border-style: solid none none none;
  border-width: 2px;
  border-color: #dddddd;
}
.foot-btn {
  flex: 1;
  width: 40%;
  height: 0.8rem;
  color: white;
  background: #2f86f6;
  border-radius: 10px;
  margin: 0.2rem;
}
</style>

<script>

export default {
  pageConfig: {
    canScroll: false,
  },
  data() {
    return {
      remark: "111",
      slogan: "~ Hello Tenon ~",
    };
  },
  created() {
    // Toast.show("Base Lifecycle On Create!");
  },
  methods: {
    success() {
      let params = {
        remark: this.remark,
      };
      Toast.show("确认" + JSON.stringify(params));

    },
    reset() {
      this.remark = "";
    },
  },
};
</script>`
[test.zip](https://github.com/didi/Hummer/files/6606316/test.zip)

**Comment by duanlikang** [comment]
感谢反馈， bug 已修复，升级 `@hummer/tenon-vue`包即可，`@hummer/tenon-vue@1.2.12`。
