### ISSUE TITLE
Request 网络请求组件 errormsg不显示

### ISSUE THREAD

**Issue by JavaXinTu** [didi/Hummer#208]
## 描述

Request 网络请求组件 errormsg不显示

## Hummer version:

@hummer/cli@0.1.27

## 复现步骤
1.修改url访问一个可以返回异常的接口
2.其中error只会返回 error:{"code":-100,"msg":"http response status error!"}  
                  IOS 只有 error: {code:0}

## 预期结果

可以返回errorMsg，及系统返回的正常的异常提示信息。

## 样例代码、屏幕截图或者仓库链接
```
var request = new Request();
request.header = { 'content-type': 'application/json' };
request.url = 'https://www.baidu.com/';
request.method = 'GET';
request.timeout = 30000;
request.param = {};
request.send((response) => {
	console.log("返回值： ok:" + response.ok);
	console.log("返回值： status:" + response.status);
	console.log("返回值： statusText:" + response.statusText);
	console.log("返回值： data:" + response.data);
	console.log("返回值： header:" + JSON.stringify(response.header));
	console.log("返回值： error:" + JSON.stringify(response.error));
});
```

**Comment by bbssyyuui** [comment]
能提供一个你期望的正常的范围信息吗？

**Comment by JavaXinTu** [comment]
restful api 返回值都在body中


code200时可以返回data 就是或data接收了body值


code非200不返回data&nbsp;


非200的时候&nbsp; data接收body值&nbsp;
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 或者 error中有返回的body值 （不仅仅是返回 code异常）




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "didi/Hummer"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年6月11日(星期五) 下午3:51
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [didi/Hummer] Request 网络请求组件 errormsg不显示 (#208)





 
能提供一个你期望的正常的范围信息吗？

**Comment by bbssyyuui** [comment]
是否可以帮忙这个包？看下在error时你具体希望收到的response格式。
或者是否可以给一个我们可以访问到错误链接？因为我们这边没有类似你说的这种场景的链接。

**Comment by JavaXinTu** [comment]
1.成功的请求
http://redmine.timogroup.com:44234/test/success
2.失败的请求1 返回json
http://redmine.timogroup.com:44234/test/error1

2.失败的请求2 返回string
http://redmine.timogroup.com:44234/test/error2







------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "didi/Hummer"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年6月14日(星期一) 中午1:08
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [didi/Hummer] Request 网络请求组件 errormsg不显示 (#208)





 
是否可以帮忙这个包？看下在error时你具体希望收到的response格式。
 或者是否可以给一个我们可以访问到错误链接？因为我们这边没有类似你说的这种场景的链接。
