### ISSUE TITLE
Tenon 中 <textarea> 限制行数后 达到行数页面卡死

### ISSUE THREAD

**Issue by JavaXinTu** [didi/Hummer#212]
## 描述

Tenon 中 <textarea> 限制行数后 达到行数页面卡死
row限制3行之后就达到就app卡死

代码示例
` <textarea
            class="input input-place input-textarea"
            rows="3"
            v-model="remark"
            placeholder=""
          />`
## Hummer version:

@hummer/cli@0.1.27
@hummer/tenon-vue@1.2.13

## 复现步骤

1. Android填写3行文字
2. 手机卡死，无法关闭输入法，只可以关闭app

## 预期结果

输入完后页面不会卡死

## 样例代码、屏幕截图或者仓库链接
` <textarea
            class="input input-place input-textarea"
            rows="3"
            v-model="remark"
            placeholder=""
          />`

**Comment by duanlikang** [comment]
感谢反馈，问题已经定位到，安卓在这种场景下，会重复触发 `input`事件，导致循环触发，计算超时。

**Comment by bbssyyuui** [comment]
安卓新版Playground App已修复此问题，可以更新一下试试

**Comment by duanlikang** [comment]
已修复，集成最新版安卓 SDK即可。
