### ISSUE TITLE
Android Tenon 中 <input> 在文字中间输入内容，光标会自动置到最后

### ISSUE THREAD

**Issue by JavaXinTu** [didi/Hummer#214]
## 描述
Android Tenon 中 <input> 移动光标到文字中间,输入一个字符后,光标移动到最后

代码示例
`<input class="input input-place" v-model="phone" placeholder="请输入" />`

## Hummer version:
@hummer/cli@0.1.27
@hummer/tenon-vue@1.2.13

## 复现步骤
1.在input中输入qweasdzxc
2.光标移动到'a'后面 输入'm' 输入成功文字变为 qweamsdzxc 光标移动到最后

## 预期结果
光标位置不变

## 样例代码、屏幕截图或者仓库链接
`<input class="input input-place" v-model="phone" placeholder="请输入" />`

**Comment by JavaXinTu** [comment]
奇怪的现象：
手机：华为mate20pro
输入法：百度输入法华为版
连续快速打字母，文字会断开，中间出现空格

**Comment by duanlikang** [comment]
问题已解决，最新版 `@hummer/tenon-vue@1.2.14`支持。
Tenon 侧增加值更新判断逻辑，`v-model`指令中，当值没有变化时，不重新赋值。
