### ISSUE TITLE
Debug模式下支持视图高亮

### ISSUE THREAD

**Issue by bbssyyuui** [didi/Hummer#254]
## 功能请求
每个视图都具有一个highlight方法，可以高亮视图本身（画框或其他高亮样式）。

## API 设计
// 高亮
view.dbg_highlight()
view.dbg_highlight(true)

// 不高亮
view.dbg_highlight(false)

// 高亮，并接收高亮时的信息配置（暂时不用，预留）
view.dbg_highlight(config)

**Comment by AdamCaoQAQ** [comment]
整挺好
