### ISSUE TITLE
WebSocket 组件对齐前端 WebSocket API

### ISSUE THREAD

**Issue by bbssyyuui** [didi/Hummer#280]
## 功能请求

- [x] 我想要完成此功能

**您的功能请求是否与一个问题有关？**

视图调试需要自动化插入 WebSocket 连接

**描述您希望的解决方案**
支持 WebSocket 标准接口

**描述您考虑过的备选方案**.

**文档、适配、迁移策略**

参考 MDN WebSocket 文档 https://developer.mozilla.org/zh-CN/docs/Web/API/WebSocket

方法：
- [ ] WebSocket(url: string)
- [ ] send(data: string)
- [ ] close()

事件：
- [ ] onopen {}
- [ ] onmessage 参数 {data?: string}
- [ ] onclose {code?: number, reason?: string}
- [ ] onerror {}

内存管理：
1. WebSocket 对象被回收不代表连接被中断，想要中断连接必须显式 close
2. JS 虚拟机关闭会关闭所有相关的连接

**Comment by ChasonTang** [comment]
iOS 先使用 SocketRocket 0.6.0 版本，未来应当兼容系统 WebSocket

**Comment by ChasonTang** [comment]
建议使用 N-API 直接注入

**Comment by bbssyyuui** [comment]
Android 已完成

**Comment by jayconscious** [comment]
hummer-front已完成
