### ISSUE TITLE
红米 k40 miui 13.0.2 安装 Hummer playground失败

### ISSUE THREAD

**Issue by ldyldyydl** [didi/Hummer#352]
## 描述
![Screenshot_2022-01-24-10-35-00-665_com miui packageinstaller](https://user-images.githubusercontent.com/50296098/150715180-2a291b15-1b7f-4761-9a6a-7feec098f51c.jpg)

## Hummer version:
"@hummer/tenon-vue": "^1.7.0",
## 复现步骤
1. hummer init 个新项目
2. npm install ，npm run dev , [下载playground](https://page.xiaojukeji.com/m/ddPage_0szxLMtT.html) 
3. 下载，安装失败

## 预期结果
安装成功

## 样例代码、屏幕截图或者仓库链接
无代码

**Comment by bbssyyuui** [comment]
问题已修复，可以重新下载安装试下：https://page.xiaojukeji.com/m/ddPage_0szxLMtT.html
