### ISSUE TITLE
Why not adapter to AndroidX?

### ISSUE THREAD

**Issue by yanglichuan** [didi/Hummer#384]
First Thanks,
I want to ask a question.
Why not adapter to AndroidX?

**Comment by bbssyyuui** [comment]
因为作为底层框架，需要兼容各种类型的App可接入，目前是support版本的主项目是无法依赖AndroidX版本的SDK的，而反过来AndroidX版本的主项目是可以依赖support版本的SDK的，所以Hummer为了保持兼容性，一直没有升级到AndroidX。
