### ISSUE TITLE
文字组件设置padding生效错误

### ISSUE THREAD

**Issue by lvzishen** [didi/Hummer#404]
您好，我是一名Android开发者。我现在使用了一个Text组件，宽和高均为auto并且设置了其 paddingLeft 和 paddingRight 分别为 5和10，但其最终出来的效果与原生 TextView 效果不符，这种情况如何解决？

**Comment by lvzishen** [comment]
我知道如果paddingLeft 和 paddingRight如果设置的值一样的话，可以通过将文字 textAlign 设置为居中解决，但如我上述所描述的情况，是否无法解决？

**Comment by bbssyyuui** [comment]
Hummer中的Text组件的padding和Android原生控件的padding确实有一些不太一样的，要实现这个效果，可以在Text组件外套一层View，给Text组件设置margin。

**Comment by lvzishen** [comment]
> Hummer中的Text组件的padding和Android原生控件的padding确实有一些不太一样的，要实现这个效果，可以在Text组件外套一层View，给Text组件设置margin。

好的，谢谢！
