### ISSUE TITLE
Tenon <scroller> 组件  scrollBy方法书写成scrolBy错误，导致无法调用到原生方法

### ISSUE THREAD

**Issue by wy676579037** [didi/Hummer#412]
, {
    key: "scrollTo",
    value: function scrollTo(x, y) {
      this.element.scrollTo(x, y);
    }
  }, {
    key: "scrollBy",
    value: function scrollBy(dx, dy) {
      this.element.scrolBy(dx, dy);
    }
  },

**Comment by AdamCaoQAQ** [comment]
This mistake has been fixed；
Changes will take effect in [the latest version ](https://www.npmjs.com/package/@hummer/tenon-vue)
