### ISSUE TITLE
CSS中visibility属性设置false时，iOS会崩溃

### ISSUE THREAD

**Issue by zhouhuishine** [didi/Hummer#414]
## 描述
我们项目中CSS属性会把visibility写成不规范的false，而不是‘hidden’。
iOS端运行时，直接把visibility的属性当做NSString来做值判断，结果导致类型不匹配，直接崩溃。

visibility属性设置成了false:
![image](https://user-images.githubusercontent.com/1219485/196079079-55d23070-5712-457c-a902-c0aba2d12afd.png)

iOS中，HMStringToViewHidden:函数(HMConverter.m:739)传入的参数为NO，NSNumber类型，不是NSString类型，调用isEqualToSrtring:函数发生崩溃。
`
+ (BOOL)HMStringToViewHidden:(NSString *)string {
    if ([string **isEqualToString**:@"hidden"]) {
        return YES;
    }
    return NO;
}
`

## Hummer version:
目前最新版本

## 复现步骤
1. CSS中为visibility属性设置false
2. 运行iOS版本

## 预期结果
希望能为**所有的取值函数**都加上类型判断进行保护，防止程序崩溃。
如下：
`
+ (BOOL)HMStringToViewHidden:(NSString *)string {
    if **([string isKindOfClass:[NSString class]]** && [string isEqualToString:@"hidden"]) {
        return YES;
    }
    return NO;
}
`

**Comment by yFeii** [comment]
请参考使用  [css 规范属性](https://developer.mozilla.org/zh-CN/docs/Web/CSS/visibility) ，规范设置属性，不符合规范导致的未定义行为，暂不处理
