### ISSUE TITLE
iOS 动画切换前后台后，动画直接结束了

### ISSUE THREAD

**Issue by QIYA0130** [didi/Hummer#416]
## Hummer version:

master分支
## 复现步骤

1.前台触发动画
2.切到后台，再切回前台

## 预期结果

动画正常继续

## 样例代码、屏幕截图或者仓库链接

let anim = new BasicAnimation('width');
anim.value = 0;
anim.duration = DataStore.progressItem.show_time;
anim.delay = 0.001;
anim.repeatCount = 1;
anim.easing = 'linear';
this.mTopProgressBar.addAnimation(anim, "animation_key");

**Comment by yFeii** [comment]
[fix](https://github.com/didi/Hummer/commit/a68768f4245c71b96fbb32eb15d972e95aeacc47)
