### ISSUE TITLE
内存不释放的问题

### ISSUE THREAD

**Issue by Niu-12138** [didi/Hummer#440]
## 描述

iOS集成后内存不释放的问题

## Hummer version

0.2.8

## 复现步骤

1. 项目集成hummer；
2. 打开tenon-vue写的页面；
3. 关闭页面后内存未释放；

如js页面使用tenon-vue项目, npm run dev 后, 将component-button下app.vue的点击事件代码改为跳自己, 如下:
```
    handleClickBtn(msg) {
      Toast.show(msg);
      let pageInfo = {
        id: '111',
        // url: 'hummer://UPPayOneTrava',
        url: 'component-button.js',
        animated: true,
        params: {
          aaa: 111,
          bbb: 222,
        }
      };
      Navigator.openPage(pageInfo, (result) => {
        console.log('Page result: ' + JSON.stringify(result));
      });
    },
```

## 预期结果

内存释放

## 样例代码、屏幕截图或者仓库链接

样例代码：https://github.com/Niu-12138/DidiHummerDemo
视屏：
https://github.com/didi/Hummer/assets/19486884/8c1c0e7f-c457-427c-8238-a0dfb88ee54c

**Comment by Niu-12138** [comment]
如何使用safari的调试功能人工触发垃圾回收？

**Comment by yFeii** [comment]
请提供下 js 工程地址

**Comment by Niu-12138** [comment]
https://github.com/didi/Hummer/tree/master/tenon

**Comment by yFeii** [comment]
![image](https://github.com/didi/Hummer/assets/24515770/d2377be2-15ba-4444-a272-766eb10fbcca)

按视频操作，无法浮现

**Comment by Niu-12138** [comment]
![image](https://github.com/didi/Hummer/assets/19486884/4894c2da-d621-41a0-ae43-2c7f2dd8b206)
![image](https://github.com/didi/Hummer/assets/19486884/17c8263c-b1ac-4b79-a019-790d60b5b5b7)

**Comment by Niu-12138** [comment]
2023.12.12，基于"hummer init"新创建的项目，也存在关闭页面后，Memory不释放，上述leaked allocations， 如图：
![image](https://github.com/didi/Hummer/assets/19486884/f0b24ba8-f8fe-4f74-899a-814adf96bb8b)

**Comment by Niu-12138** [comment]
"hummer init"新创建的项目视屏录制：

https://github.com/didi/Hummer/assets/19486884/827e0eb8-6ed4-4a92-93ce-207c6463eac1
