### ISSUE TITLE
希望能有一个现有项目集成hummer的demo，安卓和ios的

### ISSUE THREAD

**Issue by q760440238** [didi/Hummer#50]
希望能有一个现有项目集成hummer的demo，安卓和ios的

**Comment by bbssyyuui** [comment]
有几种方式哈：
1. 可以参考官方接入文档哈
Android: http://hummer.didi.cn/doc#/zh-CN/android_doc
iOS: http://hummer.didi.cn/doc#/zh-CN/ios_doc
2. 也可以直接看代码中自带的demo
3. 也可以用cli创建一个空的Android或iOS工程参考
