### ISSUE TITLE
toString 等接口表现保持于 JSC 一致，或提供新的 API

### ISSUE THREAD

**Issue by yFeii** [didi/Hummer#54]
## 功能请求

- [ ] 我想要完成此功能

**您的功能请求是否与一个问题有关？**
JSC 的 toString toNumber 会强转为目标类型，而 Hummer 存在类型判断

**描述您希望的解决方案**
提供新的于 JSC 的 toString 行为一致的方法

**描述您考虑过的备选方案**.
无

**文档、适配、迁移策略**
无

**Comment by ChasonTang** [comment]
1. toObject
2. toNumber
3. toString
4. toArray
