### ISSUE TITLE
[Android] build失败

### ISSUE THREAD

**Issue by jarlemon** [didi/Hummer#75]
## 描述
android 源码点击构建时有以下错误：
A problem occurred configuring project ':hummer-core'.
> java.lang.NullPointerException (no error message)

## Hummer version:

android 0.3.16

## 复现步骤

1.打开项目
2.点击build构建

## 样例代码、屏幕截图或者仓库链接

![image](https://user-images.githubusercontent.com/30827091/107121686-d457af00-68ce-11eb-983b-ee72684ec926.png)
![image](https://user-images.githubusercontent.com/30827091/107122434-b8eea300-68d2-11eb-8a98-98d84dff3392.png)

**Comment by bbssyyuui** [comment]
需要手动设置一下NDK版本，建议版本21及以上。
