### ISSUE TITLE
[iOS] -[UIView(HMDom) hm_layoutSubviews]	UIView+HMDom.m:809

### ISSUE THREAD

**Issue by jieliangma** [didi/Hummer#77]
内部崩溃手机平台上有个崩溃，链接：http://mas.intra.xiaojukeji.com/application/qualitydetail/100841/ios/3?appId=100841&majorVersion=3.1.2&version=3.1.2.5040&calType=1&errTagTitle=-[UIView(HMDom)%20hm_layoutSubviews]%09UIView%2BHMDom.m:809&funcEnum=1&beginTime=1612839840000&endTime=1612926240000&msgId=C19D6AA5-4087-4C79-95C0-5A11C5E05E44&handler=待分配&status=待处理&statusCode=1&parentId=bea0344ab9986444f56eab0f744ee3aa

**Comment by ChasonTang** [comment]
内部错误请直接找 @唐佳诚
