### ISSUE TITLE
iOS repeatCount 无效

### ISSUE THREAD

**Issue by yFeii** [didi/Hummer#80]
## 描述
iOS repeatCount 无效

## Hummer version:
0.2.3

## 复现步骤
None

## 预期结果
api 使用正常

## 样例代码、屏幕截图或者仓库链接
None

**Comment by duanlikang** [comment]
针对 repeatCount 的场景，按照前端的预期行为来说：
- `-1` 代表无限重复，类比于 Web 中的 `infinite`；
- `0` 代表不做动画；
- `1` 等大于 `0`的数字，代表动画执行的次数；

现在针对 `0`的预期行为，需要讨论，看下端的实现。

**Comment by yFeii** [comment]
iOS 原生行为：

- 小与 1 为 1次。
- 等于 1 的数字，代表动画执行的次数。

**Comment by bbssyyuui** [comment]
Android原生行为：

- -1：无限次；
- 0：重复0次，即动画做1次；
- 1： 重复1次，即动画做2次；

**Comment by yFeii** [comment]
结论：

- 小于0，相当于 infinate
- 0，执行1次。
- 大于等于 1 的数字，代表动画执行的次数。

默认值为=1 
@bbssyyuui @duanlikang
