### ISSUE TITLE
Tenon 提供 Tenon Router 生态包

### ISSUE THREAD

**Issue by duanlikang** [didi/Hummer#97]
## 功能请求

- [x] 我想要完成此功能

为了对接 Vue 前端生态，路由层面，需要提供类似 `Vue Router`的包，对齐 Vue Router 的 Api，便于快速实现路由间的快速切换。

**您的功能请求是否与一个问题有关？**

现在 Tenon Vue 生态中，缺乏 Vue Router，缺少一个完善的路由管理工具。在迁移 Web 项目中， 路由模块需要完全重写，成本较大。

**描述您希望的解决方案**
实现 `tenon-vue-router` 库

**描述您考虑过的备选方案**.

**文档、适配、迁移策略**

**Comment by AdamCaoQAQ** [comment]
I finished my first commit at https://github.com/OrangeLab/tenon-vue-router
Please check [here](https://github.com/OrangeLab/tenon-vue-router/issues) for any other issues
